### ISSUE TITLE
ADS-B messages preprocessed

### ISSUE THREAD

**Issue by cht11** [Ralphkaram10/Supervised_ADS_B_anomaly_detection#1]
I would like to ask you the following, how are your ADS-B messages preprocessed? 
Please add your contact information to ask for more details.

**Comment by Ralphkaram10** [comment]
Actually the datasets used in this repository (accessible by the link) are downloaded from opensky network.
For more information on the preprocessing you can refer to:
- [Supervised ADS-B anomaly detection using a false data generator](https://drive.google.com/file/u/0/d/1Cac_O0kBnJbuyN9yrm2NuapAnRKPsd_E/view)
- [Automatic detection of business data anomalies with deep learning and application to the ADS-B protocol](https://theses.hal.science/tel-04060949/)

**Comment by Ralphkaram10** [comment]
You can contact me on: ralphkaram10@gmail.com

**Comment by Ralphkaram10** [comment]
I can give you my contact information. But it is preferable to contact me here so others can profit from the discussion.

**Comment by cht11** [comment]
> Actually the datasets used in this repository (accessible by the link) are downloaded from opensky network. For more information on the preprocessing you can refer to:
> 
> * [Supervised ADS-B anomaly detection using a false data generator](https://drive.google.com/file/u/0/d/1Cac_O0kBnJbuyN9yrm2NuapAnRKPsd_E/view)
> * [Automatic detection of business data anomalies with deep learning and application to the ADS-B protocol](https://theses.hal.science/tel-04060949/)

Ok, I understand. Thank you for your reply！

**Comment by Ralphkaram10** [comment]
You’re welcome!

**Comment by cht11** [comment]
> Actually the datasets used in this repository (accessible by the link) are downloaded from opensky network. For more information on the preprocessing you can refer to:
> 
> * [Supervised ADS-B anomaly detection using a false data generator](https://drive.google.com/file/u/0/d/1Cac_O0kBnJbuyN9yrm2NuapAnRKPsd_E/view)
> * [Automatic detection of business data anomalies with deep learning and application to the ADS-B protocol](https://theses.hal.science/tel-04060949/)

Excuse me, I can't find where to download your dataset in opensky. Could you please give me the website for downloading your dataset

**Comment by Ralphkaram10** [comment]
- I actually wrote a script to download (allegedly normal) asds-b messages in sbs format (using https://github.com/xoolive/traffic/ library which uses opensky network).
- Then I wrote a script that transforms sbs messages to meta messages.
- I will try to rewrite these scripts more cleanly and push to this repository by the end of the weekend.
- Note that the attacks parts of the flights are generated using a proprietary software which I don't own and cannot push. That is why only the datasets were disclosed in this repo and not the generation part.

**Comment by cht11** [comment]
> * I actually wrote a script to download (allegedly normal) asds-b messages in sbs format (using https://github.com/xoolive/traffic/ library which uses opensky network).
> * Then I wrote a script that transforms sbs messages to meta messages.
> * I will try to rewrite these scripts more cleanly and push to this repository by the end of the weekend.
> * Note that the attacks parts of the flights are generated using a proprietary software which I don't own and cannot push. That is why only the datasets were disclosed in this repo and not the generation part.

Ok, thank you very much for your reply. My current problem is: I have raw message data for ADS-B and I'm thinking about how to process it into your csv file format.

**Comment by Ralphkaram10** [comment]
Actually I downloaded the raw format using [traffic](https://github.com/xoolive/traffic/) library. [traffic](https://github.com/xoolive/traffic/) library then allows you to decode those raw messages in a format similar to sbs. This new format contains explicit fields such as ground speed, altitude, etc. Therefore it is easy to transform this explicit format in the meta messages format (my csv file format).

Anyway I will try to rewrite those scripts. 

You are welcome !

**Comment by Ralphkaram10** [comment]
I added scripts to the repo:
download_sbs.py (to download raw messages and turn them into the sbs format)
SBS_to_Meta.py (to turn sbs format into meta messages)
plot_flight.py (Plot the specified feature of a file of meta messages corresponding to one flight)

Note that download_sbs.py is slow to download and process flights, also some flights may not be downloadable.
But it can be enough to get you to download a reasonable number of flights.

**Comment by cht11** [comment]
> I added scripts to the repo: download_sbs.py (to download raw messages and turn them into the sbs format) SBS_to_Meta.py (to turn sbs format into meta messages) plot_flight.py (Plot the specified feature of a file of meta messages corresponding to one flight)
> 
> Note that download_sbs.py is slow to download and process flights, also some flights may not be downloadable. But it can be enough to get you to download a reasonable number of flights.

oh! nice!!!!! 
I'm truly grateful for adding these scripts to the open-source project. Your work will be immensely helpful for my project. 
Thanks again for your response and addressing my questions!!!!!!

**Comment by Ralphkaram10** [comment]
I hope these will be helpful to you! My pleasure !!!!!!
